server:
  port: 8099
spring:
  application:
    name: nacos-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: json
        name: ${spring.application.name}.
# 自动加载注册中心中的lb,开启后无需配置
    gateway:
      discovery:
        locator:
          enabled: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
